### ISSUE TITLE
Question: Implement Set on Gauge

### ISSUE THREAD

**Issue by mr-karan** [VictoriaMetrics/metrics#11]
I strumbled across a common pitfall in Go wrt Closures. Consider the code:

```
func (s *stats) Set(label string, val float64) {
	val2 := val
	s.metrics.GetOrCreateGauge(label, func() float64 {
		return val2
	})
}
```

- When `s.Set()` is called for the first time the value of `val` and `val2` is same.
- When `s.Set()` is invoked the next time the value of `val` updates but `val2` is still the same.

This strange behavior happens because `Gauge` [stores](https://github.com/VictoriaMetrics/metrics/blob/master/gauge.go#L29) the function closure inside the struct. Any future invocations don't update the function and the user sees the old value. 

The workaround was to put the value in a map first and inside function closure, lookup on the map to get the key.

```
func (s *stats) Set(label string, val float64) {
	s.Lock()
	defer s.Unlock()
	s.guages[label] = val
	s.metrics.GetOrCreateGauge(label, func() float64 {
		return s.guages[label]
	})
}
```

I am not sure but storing a closure inside `Gauge` does not seem like a proper API to me. Is there any reason why a `.Set(float64)` method can't be provided and why a `func() float64` has to be passed instead? The `Gauge` API can be similar to [`Counter.Set`](https://github.com/VictoriaMetrics/metrics/blob/master/counter.go#L50) method which takes a `uint64`.

This took a lot of time to figure out so documenting in case anyone else also comes across this behaviour.

**Comment by valyala** [comment]
It is expected that [Gauge](https://godoc.org/github.com/VictoriaMetrics/metrics#Gauge) is initialized only once per metric and this initialization is usually performed during program startup. Then the `func() float64` callback is called every time [WritePrometheus](https://godoc.org/github.com/VictoriaMetrics/metrics#WritePrometheus) is called.

It is likely you need [FloatCounter](https://godoc.org/github.com/VictoriaMetrics/metrics#FloatCounter) instead of `Gauge`. The `FloatCounter` has [Set method](https://godoc.org/github.com/VictoriaMetrics/metrics#FloatCounter.Set), which ideally fits your case:

```go
func (s *stats) Set(label string, val float64) {
	s.metrics.GetOrCreateFloatCounter(label).Set(val)
}
```

**Comment by mr-karan** [comment]
Ah this makes sense. It's a bit different from the official client_golang Prometheus library hence the confusion.

Sorry to bother you and thanks for answering :) Closing this.

**Comment by valyala** [comment]
Updated docs in the commit fd1ac75aa05ee8090d43c977e7e5ab3033bb8c27 , so it will be more clear that `FloatCounter` can be used instead of `Gauge` for floating-point values.
