### ISSUE TITLE
how to update gauge value?

### ISSUE THREAD

**Issue by lancedang** [VictoriaMetrics/metrics#62]

**Comment by hagen1778** [comment]
Hey @lancedang! Please see example here https://pkg.go.dev/github.com/VictoriaMetrics/metrics#example-Gauge

**Comment by valyala** [comment]
It is also possible to (ab)use [Counter](https://pkg.go.dev/github.com/VictoriaMetrics/metrics#Counter) or [FloatCounter](https://pkg.go.dev/github.com/VictoriaMetrics/metrics#FloatCounter) as a gauge by calling the [Counter.Set](https://pkg.go.dev/github.com/VictoriaMetrics/metrics#Counter.Set) or [FloatCounter.Set](https://pkg.go.dev/github.com/VictoriaMetrics/metrics#FloatCounter.Set) in order to update its value.

**Comment by hagen1778** [comment]
@lancedang with https://github.com/VictoriaMetrics/metrics/pull/61#issuecomment-1864369247 it is now possible to call `.Set` method for gauges.
